updates related to hostname_alt upgrade

diff --git a/common_AOK/hostname_handling/hostname_alt b/common_AOK/hostname_handling/hostname_alt
--- a/common_AOK/hostname_handling/hostname_alt
+++ b/common_AOK/hostname_handling/hostname_alt
@@ -28,6 +28,11 @@
 #      as you use in the iOS shortcut
 
 show_help() { # Multi OK 1
+    if ! this_is_ish; then
+        echo
+        echo "WARNING: this is only meaningfull on iSH"
+        echo
+    fi
     echo "Usage: hostname [-h] [-U] [ -S /full/path/to/sourcefile ]
 
 Uses hint provided by shortcut to update hostname
@@ -49,100 +54,88 @@ Available options:
 Custom options for this hostname implementation:
 
 -S  --sourcefile   Informs this tool what file to check for the shortcut hint
-                   Special case, if this is /etc/hostname content will not
-                   be cached, just displayed"
-    help_show_source_file
-    echo "
+                   Special case, if this is /etc/hostname it is assumed
+                   that hostname is static. Current source file:
+                    $(get_sync_file_fn)
+
 -U  --update       Re-read sourcefile. If sourcefile is /etc/hostname
                    nothing happens. For any other sourcefile, hostname
                    will be asumed to be the last line in the sourcefile
                    and it will be copied to /etc/hostname, to be used.
                    Be aware if you use this on multiple devices the
-                   source file will contain the name of the latest iSH started,
-                   in such cases do this update just after starting this instance.
+                   source file will contain the name of the latest iSH
+                   started, in such cases do this update just after starting
+                   this instance.
                    AOK-FS provides /usr/local/sbin/hostname_sync.sh and
                    runs it from inittab at startup to do this update
 
-All other options are ignored, in order to be compatible with the default
-hostnme"
+All other options are ignored, for compatibility with the default hostnme"
     exit 0
 }
 
-help_show_source_file() {
-    if [ -n "$f_src_file" ]; then
-        echo "                   Current source file: $f_src_file"
-    fi
+error_msg() {
+    echo
+    echo "ERROR: $1"
+    echo
+
+    exit 1
 }
-read_source_file_name() {
+
+#read_source_file_name() {
+get_sync_file_fn() {
     if [ -z "$hostname_source_fname" ] || [ ! -f "$hostname_source_fname" ]; then
-        f_src_file=""
+        # f_src_file=""
+        echo ""
     else
-        f_src_file="$(cat "$hostname_source_fname" 2>/dev/null)"
+        cat "$hostname_source_fname"
     fi
 }
 
-hostname_read() {
-    ! this_is_aok_kernel && return
+use_syncfile() {
     #
-    #  iSH-AOK can set hostname, so once this is done things
-    #  hardcoded to /bin/hostname will use the intended hostname
+    #  Copies last line of sync file to /etc/hosts
     #
-    /bin/hostname -F /etc/hostname
-}
-
-do_sync_hostname() {
-    # msg_2 "do_sync_hostname(()"
-
-    if [ -z "$f_src_file" ]; then
-        error_msg "No sourcefile defined!"
-    elif [ ! -f "$f_src_file" ]; then
-        error_msg "source file ($f_src_file) not pressent!"
-    fi
 
     #
-    #  Use last line of file as hostname
+    #  First find sync file
     #
-    awk 'END {print $1}' "$f_src_file" >"$hostname_cached"
+    fn_sync_file="$(get_sync_file_fn)"
+    [ -z "$fn_sync_file" ] && error_msg "No sync file defined!"
+    [ -f "$fn_sync_file" ] || error_msg "sync file '$fn_sync_file' not found!"
 
-    cp "$hostname_cached" /etc/hostname
+    #
+    #  If /etc/hostname is used as sync file, it implies static hostname
+    #  nothing needs to be done
+    #
+    [ "$fn_sync_file" = "/etc/hostname" ] && return
 
     #
-    #  Since only the last line is of interest normally, make sure
-    #  f_src_file doesnt grow to much, especially if multiple devices
-    #  write to the same file each time they start
+    #  Use last line of sync file as hostname
     #
-    if [ "$(wc -l <"$f_src_file")" -gt 25 ]; then
+    awk 'END {print $1}' "$fn_sync_file" | sudo tee /etc/hostname >/dev/null
+
+    #
+    #  iSH-AOK can set hostname, so once this is done things hardcoded
+    #  to use the default /bin/hostname will use the intended hostname
+    #
+    grep -qi aok /proc/ish/version 2>/dev/null && sudo /bin/hostname -F /etc/hostname
+
+    #
+    #  Since only the last line is of interest, and the shortcut keeps
+    #  adding new ones, make sure fn_sync_file doesnt grow to much
+    #
+    if [ "$(wc -l <"$fn_sync_file" | awk '{ print $1 }')" -gt 15 ]; then
         # Truncate the file to the last 10 lines
-        tail -n 10 "$f_src_file" >/tmp/sync_file
-        mv /tmp/sync_file "$f_src_file"
+        tail -n 10 "$fn_sync_file" >/tmp/sync_file
+
+        #
+        #  If sync file is on iCloud, iCloud is owned by a user
+        #  and this is run as root, there will be an error printed
+        #  since owner of dest cant be changed to root (!)
+        #  However the file is still copied, so it can be ignored
+        #
+        mv /tmp/sync_file "$fn_sync_file" 2>/dev/null
     fi
-
-    # msg_3 "do_sync_hostname(() - done"
-}
-
-do_update() {
-    rm -f "$hostname_cached"
-    get_hostname
-    exit 0
-}
-
-get_hostname() {
-    # msg_2 "get_hostname(()"
-
-    if [ -z "$f_src_file" ]; then
-        echo "ERROR: no source file defined, run with -h to see help!"
-        exit 1
-    fi
-
-    #
-    #  If source file is /etc/hostname, then no syncing is needed, used
-    #  for manual setting of post iOS 17 hostname
-    #
-    [ "$f_src_file" != "/etc/hostname" ] && do_sync_hostname
-
-    hostname_read
-
-    # msg_3 "get_hostname(() - done"
 }
 
 #===============================================================
@@ -152,9 +145,9 @@ get_hostname() {
 #===============================================================
 
 # shellcheck source=/opt/AOK/tools/utils.sh
-. /opt/AOK/tools/utils.sh
+#. /opt/AOK/tools/utils.sh
 
-read_source_file_name
+hostname_source_fname=/etc/opt/hostname_source_fname
 
 while [ -n "$1" ]; do
 
@@ -163,7 +156,7 @@ while [ -n "$1" ]; do
     "-h" | "--help") show_help ;;
 
     #  ignored, but accepted for compatability
-    "-f" | "--fqdn" | "--long" | "-s" | "--short") ;;
+    # "-f" | "--fqdn" | "--long" | "-s" | "--short") ;;
 
     "-S" | "--sourcefile")
         sync_file="$2"
@@ -174,35 +167,18 @@ while [ -n "$1" ]; do
             error_msg "-S / --sourcefile file not found: $sync_file"
         fi
         echo "$sync_file" >"$hostname_source_fname"
-        read_source_file_name
-
-        #
-        #  To ensure the hostname from the source file is picked up,
-        #  clear the current name
-        #
-        do_update
+        #  Read sync file and take action
+        use_syncfile
         ;;
 
     "-U" | "--update")
-        do_update
+        use_syncfile
         ;;
 
-    *) ;;
+    *) ;; #
 
     esac
     shift
-
 done
-
-if [ "$f_src_file" = "/etc/hostname" ]; then
-    #
-    #  If it has changed, reread if for /bin/hostname on iSH-AOK
-    #
-    s_etc_hostname="$(cat /etc/hostname)"
-    s_cached="$(cat "$hostname_cached" 2>/dev/null)"
-    [ "$s_etc_hostname" != "$s_cached" ] && hostname_read
-else
-    [ ! -f "$hostname_cached" ] && get_hostname
-fi
 
 cat /etc/hostname
