blocking some apps when chrooted

diff --git a/common_AOK/usr_local_bin/disable_sshd b/common_AOK/usr_local_bin/disable_sshd
--- a/common_AOK/usr_local_bin/disable_sshd
+++ b/common_AOK/usr_local_bin/disable_sshd
@@ -5,6 +5,11 @@
 #  License: MIT
 #
 
+if [ -f /etc/opt/AOK/is_chrooted ]; then
+    echo "This can't be run when chrooted!"
+    exit 1
+fi
+
 if [ -f /etc/alpine-release ]; then
     srvc_name="sshd"
 elif [ -f /etc/debian_version ]; then
diff --git a/common_AOK/usr_local_bin/enable_sshd b/common_AOK/usr_local_bin/enable_sshd
--- a/common_AOK/usr_local_bin/enable_sshd
+++ b/common_AOK/usr_local_bin/enable_sshd
@@ -7,6 +7,11 @@
 # Enable sshd to run automatically
 #
 
+if [ -f /etc/opt/AOK/is_chrooted ]; then
+    echo "This can't be run when chrooted!"
+    exit 1
+fi
+
 if [ -f /etc/alpine-release ]; then
     srvc_name="sshd"
 elif [ -f /etc/debian_version ]; then
@@ -16,7 +21,7 @@ else
     exit 1
 fi
 
-sudo rc-update add "$srvc_name"
+sudo rc-update add "$srvc_name" default
 
 sudo rc-service "$srvc_name" start
 
