Verification before changing TZ

diff --git a/common_AOK/usr_local_bin/set-timezone b/common_AOK/usr_local_bin/set-timezone
--- a/common_AOK/usr_local_bin/set-timezone
+++ b/common_AOK/usr_local_bin/set-timezone
@@ -10,19 +10,6 @@
 #  https://gist.github.com/eduardoaugustojulio/fa83cf85efa39919d6a70ca679e91f28
 #
 
-# dialog_app="dialog"
-dialog_app="whiptail"
-
-# if [[ -d /etc/apt ]] || [[ -f /etc/alpine-release ]] && [[
-#     "$(sed 's/\./ /g' /etc/alpine-release | awk '{print $1"."$2 }')" = "3.14" ]] \
-#     ; then
-#     #
-#     #  Older Alpines and supported Debians use a dialog version not able
-#     #  to handle arrows,so whiptail is enforced
-#     #
-#     dialog_app="whiptail"
-# fi
-
 # do_clear() {
 #     #
 #     #  dialog ueses an option too clear screen after an item is displayed
@@ -133,14 +120,35 @@ main() {
         #  selected, the outermost layer of this will use it once exiting.
         #
         main
+    fi
+
+    if ! $dialog_app --yesno "Setting Time Zone to:\n\n    $region/$tz\n" 0 0; then
+        #  recurse and try again
+        main
     else
         tZone="$region/$tz"
     fi
 }
 
-if [[ "$(whoami)" != 'root' ]]; then
-    echo "You must use sudo or run as root"
-    exit 1
+#===============================================================
+#
+#   Main
+#
+#===============================================================
+
+# dialog_app="dialog"
+dialog_app="whiptail"
+
+# execute again as root
+if [[ "$(whoami)" != "root" ]]; then
+    echo "Executing as root"
+    # using $0 instead of full path makes location not hardcoded
+    if ! sudo "$0" "$@"; then
+        echo
+        echo "ERROR: Failed to sudo $0"
+        echo
+    fi
+    exit 0
 fi
 
 check_dependencies
@@ -152,7 +160,6 @@ if test -n "$tZone"; then
     #  Use the selected time-zone
     #
     ln -sf "/usr/share/zoneinfo/$tZone" /etc/localtime
-    $dialog_app --msgbox "Time Zone is now:\n\n $tZone\n" 0 0
 fi
 
 # do_clear
