shutdown requires root privs

diff --git a/common_AOK/usr_local_bin/shutdown b/common_AOK/usr_local_bin/shutdown
--- a/common_AOK/usr_local_bin/shutdown
+++ b/common_AOK/usr_local_bin/shutdown
@@ -18,6 +18,12 @@
 
 notification="${1:-This machine will be shutdown in 10 seconds}"
 
+uid="$(id | awk -F'[(=]' '{print $2}')"
+
+if [ $uid -ne 0 ]; then
+    echo "ERROR $0 requires root privileges!"
+    exit 1
+fi
 if test -f /etc/alpine-release; then
     wall_cmd="/usr/local/bin/wall"
 else
