prevent from running if not iSH-AOK kernel

diff --git a/common_AOK/usr_local_bin/toggle_multicore b/common_AOK/usr_local_bin/toggle_multicore
--- a/common_AOK/usr_local_bin/toggle_multicore
+++ b/common_AOK/usr_local_bin/toggle_multicore
@@ -10,19 +10,16 @@ version="2.0.0  2022-05-25"
 
 prog_name=$(basename "$0")
 
-
-if [ ! -e /proc/ish/defaults/enable_multicore ]; then
-   echo "Not running on iSH-AOK, exiting."
-   exit 1
+if ! grep -qi aok /proc/ish/version 2>/dev/null; then
+    echo "Not running on iSH-AOK, exiting."
+    exit 1
 fi
-
 
 # execute again as root
 if [ "$(whoami)" != "root" ]; then
-     sudo "$0" "$1"
-     exit 0
+    sudo "$0" "$1"
+    exit 0
 fi
-
 
 show_status() {
     STATE="$(cat /proc/ish/defaults/enable_multicore)"
@@ -32,7 +29,6 @@ show_status() {
         echo "off"
     fi
 }
-
 
 usage() {
     echo "Version:  $version"
@@ -46,33 +42,32 @@ usage() {
     show_status
 }
 
-
 case "$1" in
 
-    "" | "-h" | "--help" )
-	usage
-	exit 0
-	;;
+"" | "-h" | "--help")
+    usage
+    exit 0
+    ;;
 
-    "on" )
-	echo "true" > /proc/ish/defaults/enable_multicore
-	exit 0
-	;;
+"on")
+    echo "true" >/proc/ish/defaults/enable_multicore
+    exit 0
+    ;;
 
-    "off" )
-	echo "false" > /proc/ish/defaults/enable_multicore
-	exit 0
-	;;
+"off")
+    echo "false" >/proc/ish/defaults/enable_multicore
+    exit 0
+    ;;
 
-    "status" )
-	show_status
-	exit 0
-	;;
+"status")
+    show_status
+    exit 0
+    ;;
 
-    * )
-	echo "ERROR: Unknown option $1"
-	echo
-	usage
-	exit 1
-	;;
+*)
+    echo "ERROR: Unknown option $1"
+    echo
+    usage
+    exit 1
+    ;;
 esac
