linting

diff --git a/build_fs b/build_fs
--- a/build_fs
+++ b/build_fs
@@ -18,24 +18,22 @@ prog_name=$(basename "$0")
 #  shellcheck disable=SC1091
 . /opt/AOK/BUILD_ENV
 
-
 #
 #  Point to AOK-Filesystem-Tools dir, in case this was run with a path
 #
 #  shellcheck disable=SC1007
 cd "$AOK_CONTENT" || exit 1
 
-verbose=false              # true displays tar/untar progress
-use_bzip2=false            # Use tgz when compressing image
-build_debian_FS=false      # true means build Debian FS
-distro_select=false        # true means choose between Alpine and Debian
-pre_build_FS=false         # true meand generat4 pre-built FS
-aok_FS_do_compress=true    # compress FS at end of build_fs
+verbose=false           # true displays tar/untar progress
+use_bzip2=false         # Use tgz when compressing image
+build_debian_FS=false   # true means build Debian FS
+distro_select=false     # true means choose between Alpine and Debian
+pre_build_FS=false      # true meand generat4 pre-built FS
+aok_FS_do_compress=true # compress FS at end of build_fs
 
 aok_files="${BUILD_ROOT_D}${AOK_CONTENT}"
 
-
-show_help() {  # Multi OK 1
+show_help() { # Multi OK 1
     cat <<EOF
 $prog_name, version $version
 
@@ -66,50 +64,50 @@ EOF
     exit 0
 }
 
-parse_arguments() {  # Multi OK 1
+parse_arguments() { # Multi OK 1
     while [ -n "$1" ]; do
 
         case "$1" in
 
-            "-h" | "--help" ) show_help ;;
+        "-h" | "--help") show_help ;;
 
-            "-V" | "--version" ) show_version ;;
+        "-V" | "--version") show_version ;;
 
-            "-v" | "--verbose" ) verbose=true ;;
+        "-v" | "--verbose") verbose=true ;;
 
-            "-d" | "--debian" ) build_debian_FS=true ;;
+        "-d" | "--debian") build_debian_FS=true ;;
 
-            "-s" | "--select" )
-                if $pre_build_FS ; then
-                    echo "-p and -d can not be combined!"
-                    exit 1
-                fi
-                distro_select=true
-                ;;
-
-            "-p" | "--prebuilt" )
-                if $distro_select ; then
-                    echo "-p and -d can not be combined!"
-                    exit 1
-                fi
-                pre_build_FS=true
-                ;;
-
-            "-j" | "--bzip2" ) use_bzip2=true ;;
-
-            "-N" |  "--no_compress" ) aok_FS_do_compress=false ;;
-
-            *)
-                echo "ERROR: bad param, try -h"
+        "-s" | "--select")
+            if $pre_build_FS; then
+                echo "-p and -d can not be combined!"
                 exit 1
-                ;;
+            fi
+            distro_select=true
+            ;;
+
+        "-p" | "--prebuilt")
+            if $distro_select; then
+                echo "-p and -d can not be combined!"
+                exit 1
+            fi
+            pre_build_FS=true
+            ;;
+
+        "-j" | "--bzip2") use_bzip2=true ;;
+
+        "-N" | "--no_compress") aok_FS_do_compress=false ;;
+
+        *)
+            echo "ERROR: bad param, try -h"
+            exit 1
+            ;;
 
         esac
         shift
     done
 }
 
-show_version() {  # Multi OK 1
+show_version() { # Multi OK 1
     echo "$prog_name $version"
     exit 0
 }
@@ -117,20 +115,20 @@ show_version() {  # Multi OK 1
 ensure_usable_wget() {
     msg_2 "ensure_usable_wget()"
     #  shellcheck disable=SC2010
-    if ls -l "$(command -v wget)" | grep -q busybox ; then
+    if ls -l "$(command -v wget)" | grep -q busybox; then
         error_msg "You need to install a real wget, busybox does not handle redirects"
     fi
     # msg_3 "ensure_usable_wget()  done"
 }
 
-display_build_env() {  # Multi OK 1
+display_build_env() { # Multi OK 1
     #
     #  Displaying build environment
     #
     [ "$BUILD_ENV" -eq 1 ] && run_mode="Building on iSH"
     [ "$BUILD_ENV" -eq 2 ] && run_mode="Building on x86 Linux"
 
-    if ! $pre_build_FS ; then
+    if ! $pre_build_FS; then
         run_mode="Will not chroot"
         run_mode="$run_mode, $AOK_CONTENT files will be copied"
     elif [ "$BUILD_ENV" -eq 0 ]; then
@@ -141,13 +139,11 @@ display_build_env() {  # Multi OK 1
     fi
     msg_1 "Run mode: $run_mode"
 
-
     if [ "$(whoami)" != "root" ]; then
         # Must come after help display, to avoid infinite loop
         "$0" -h
         error_msg "This must be run as root or using sudo!"
     fi
-
 
     # if build_status_get "$STATUS_BEING_BUILT" ; then
     #     error_msg "Can't build a new env whilst the current is being built!"
@@ -160,15 +156,14 @@ display_build_env() {  # Multi OK 1
         exit 1
     fi
 
-
     msg_1 "Building a $ALPINE_RELEASE  filesystem"
 
-    if ! $aok_FS_do_compress ; then
+    if ! $aok_FS_do_compress; then
         msg_2 "*** Will not create the compressed image! ***"
     fi
 }
 
-clear_build_env() {  # Multi OK 1
+clear_build_env() { # Multi OK 1
     msg_2 "clear_build_env()"
     #
     # Clear build env
@@ -182,7 +177,7 @@ clear_build_env() {  # Multi OK 1
     # msg_3 "clear_build_env() done"
 }
 
-cache_miniroot_fs() {  # Multi OK 1
+cache_miniroot_fs() { # Multi OK 1
     msg_2 "cache_miniroot_fs()"
     #
     #  Create miniroot fs cache dir if not present, cd to it and if download
@@ -224,12 +219,12 @@ integrate_overrides() {
     conf_file="$1"
     case "$conf_file" in
 
-        AOK_VARS | BUILD_ENV ) ;;
+    AOK_VARS | BUILD_ENV) ;;
 
-        *)
-            echo "ERROR: integrate_overrides($conf_file) - bad param"
-            exit 1
-            ;;
+    *)
+        echo "ERROR: integrate_overrides($conf_file) - bad param"
+        exit 1
+        ;;
 
     esac
 
@@ -239,11 +234,10 @@ integrate_overrides() {
             echo
             echo "# ---   inherrited overrides   ---"
             echo
-        } >> "$aok_files"/"$conf_file"
-        cat "$AOK_CONTENT"/."$conf_file" >> "$aok_files"/"$conf_file"
+        } >>"$aok_files"/"$conf_file"
+        cat "$AOK_CONTENT"/."$conf_file" >>"$aok_files"/"$conf_file"
     fi
 }
-
 
 copy_AOK_to_dest() {
     #
@@ -255,13 +249,13 @@ copy_AOK_to_dest() {
     mkdir -p "$BUILD_ROOT_D"/etc/opt
     build_status_set "$STATUS_BEING_BUILT"
 
-    rsync -ah                                       \
-        --exclude=.git/                             \
-        --exclude=.gitignore                        \
-        --exclude=.gitmodules                       \
-        --exclude=.vscode/                          \
-        --exclude=.AOK_VARS                         \
-        --exclude=.BUILD_ENV                        \
+    rsync -ah \
+        --exclude=.git/ \
+        --exclude=.gitignore \
+        --exclude=.gitmodules \
+        --exclude=.vscode/ \
+        --exclude=.AOK_VARS \
+        --exclude=.BUILD_ENV \
         "$AOK_CONTENT" "$BUILD_ROOT_D"/opt
 
     integrate_overrides AOK_VARS
@@ -283,7 +277,7 @@ add_additional_tasks_if_defined() {
         {
             echo "#!/bin/sh"
             echo "$FIRST_BOOT_ADDITIONAL_TASKS"
-        }  > "$ADDITIONAL_TASKS_SCRIPT"
+        } >"$ADDITIONAL_TASKS_SCRIPT"
         chmod 755 "$ADDITIONAL_TASKS_SCRIPT"
         msg_2 "setup FIRST_BOOT_ADDITIONAL_TASKS to be run in $ADDITIONAL_TASKS_SCRIPT"
     fi
@@ -350,13 +344,19 @@ select_distro_on_1st_boot() {
     # msg_3 "select_distro_on_1st_boot()  done"
 }
 
+display_build_time() {
+    duration="$(($(date +%s) - t_start))"
+    printf "\nTime elapsed for build: %ss\n" "$duration"
 
+}
 
 #===============================================================
 #
 #   Main
 #
 #===============================================================
+
+t_start="$(date +%s)"
 
 parse_arguments "$@"
 
@@ -366,13 +366,13 @@ msg_2 "Preparing build environment"
 
 clear_build_env
 
-if $build_debian_FS ; then
+if $build_debian_FS; then
     msg_2 "Create $BUILD_ROOT_D, copy Debian FS"
     cache_Debian_fs
     mkdir -p "$BUILD_ROOT_D"
     cd "$BUILD_ROOT_D" || exit 1
     msg_2 "Extracting Debian tarball"
-    if $verbose ; then
+    if $verbose; then
         options="xfvj"
     else
         options="xfj"
@@ -389,7 +389,7 @@ else
     cache_miniroot_fs
     mkdir -p "$BUILD_ROOT_D"
     cd "$BUILD_ROOT_D" || exit 1
-    if $verbose ; then
+    if $verbose; then
         options="xfvz"
     else
         options="xfz"
@@ -408,11 +408,11 @@ msg_2 "Stored $AOK_CONTENT on new filesystem"
 
 add_additional_tasks_if_defined
 
-if $pre_build_FS ; then
+if $pre_build_FS; then
     setup_Alpine_in_advance
-elif $build_debian_FS ; then
+elif $build_debian_FS; then
     select_profile "$PROFILE_DEBIAN_COMPLETE_DEPLOY"
-elif $distro_select ;  then
+elif $distro_select; then
     select_distro_on_1st_boot
 else
     setup_Alpine_on_1st_boot
@@ -425,28 +425,26 @@ fi
 rm "$BUILD_ROOT_D"/etc/motd
 msg_2 "removed initial /etc/motd from new filesystem"
 
-
 # Should always happen
 msg_2 "created directory /iCloud inside new filesystem"
 mkdir "$BUILD_ROOT_D"/iCloud
-
 
 msg_1 "The filesystem is ready!"
 
 #
 #  Consider to generate a tarball
 #
-if $aok_FS_do_compress ; then
+if $aok_FS_do_compress; then
     extra_params=""
-    if $verbose ; then
+    if $verbose; then
         extra_params="-v"
     fi
-    if $use_bzip2 ; then
+    if $use_bzip2; then
         extra_params="$extra_params -j"
     fi
-    if $build_debian_FS ; then
+    if $build_debian_FS; then
         label="-l Debian-ish-AOK-$AOK_VERSION"
-    elif $distro_select ; then
+    elif $distro_select; then
         #  shellcheck disable=SC2154
         label="-l SelectDistro-$AOK_VERSION"
     else
@@ -457,9 +455,10 @@ if $aok_FS_do_compress ; then
     if ! "$AOK_CONTENT"/compress_image $label $extra_params; then
         error_msg "detected in compress_image"
     fi
+    display_build_time
 else
     if [ "$BUILD_ENV" -gt 0 ]; then
-        if $pre_build_FS ; then
+        if $pre_build_FS; then
             set_shell=""
         else
             set_shell="/bin/ash"
@@ -481,5 +480,6 @@ else
         echo "a fresh instance."
     fi
     echo
+    display_build_time
     exit 0
 fi
