reorganized error msgs

diff --git a/build_fs b/build_fs
--- a/build_fs
+++ b/build_fs
@@ -22,6 +22,25 @@ main_param="$1"
 skip_finalize="dont_compress"
 
 
+if [ "$(uname -s)" = "Darwin" ]; then
+    echo "Unfortunately this does not run on MacOS at this time"
+    exit 1
+fi
+
+if [ "$(whoami)" != "root" ]; then
+    echo "ERROR: This must be run as root or using sudo!"
+    echo
+    "$FS_BUILD_D/$prog_name" -h
+    exit 1
+fi
+
+if [ "$(find $BUILD_ROOT_D/dev | wc -l)" -gt 1 ]; then
+    echo "ERROR: Active chroot session detected!"
+    exit 1
+fi
+
+
+
 case "$main_param" in
 
     "-h" | "--help")
@@ -49,13 +68,6 @@ case "$main_param" in
 
 esac
 
-if [ "$(whoami)" != "root" ]; then
-    echo "ERROR: This must be run as root or using sudo!"
-    echo
-    "$FS_BUILD_D/$prog_name" -h
-    exit 1
-fi
-
 
 echo
 echo "=====  Building a $ALPINE_RELEASE iSH-AOK filesystem  ====="
@@ -63,11 +75,6 @@ echo
 
 if [ "$main_param" = "$skip_finalize" ]; then
     echo "*** Will not create the compressed image! ***"
-fi
-
-if [ "$(uname -s)" = "Darwin" ]; then
-    echo "Unfortunately this does not run on MacOS at this time"
-    exit 1
 fi
 
 
