Adding Debian support and tons of other fixes

diff --git a/BUILD_ENV b/BUILD_ENV
--- a/BUILD_ENV
+++ b/BUILD_ENV
@@ -1,35 +1,197 @@
 #!/bin/sh
 # This is sourced. Fake bang-path to help editors and linters
-#  shellcheck disable=SC2034
-
+#  shellcheck disable=SC2034,SC2154
 #
 #  Part of https://github.com/emkey1/AOK-Filesystem-Tools
 #
 #  License: MIT
 #
+#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
+#
 #  Environment variables used when building the AOK-FS
 #
 
+#
+#  To make things simple, this is the expected location for AOK-Filesystem-tools
+#  both on build and iSH systems
+#
+AOK_CONTENT="/opt/AOK"
+
+# Locations for building File systems
+BUILD_BASE_D="/tmp/AOK"
+
+
+#  shellcheck disable=SC1091
+. "$AOK_CONTENT"/AOK_VARS || exit 1
+
+
+error_msg() {
+    msg="$1"
+    exit_code="${2:-1}"
+    if [ -z "$msg" ]; then
+        echo
+        echo "error_msg() no param"
+        exit 9
+    fi
+    echo
+    echo "ERROR: $msg"
+    echo
+    [ "$exit_code" -ne 0 ] && exit "$exit_code"
+}
 
 #
-#  First case used when inside the Filesystem
-#  second case used during build
+#  The msg_ functions are ordered, lower number infers more important updates
+#  so they should stand out more
 #
-if [ -f ./AOK_VARS ]; then
-    . ./AOK_VARS || exit 1
+msg_1() {
+    [ -z "$1" ] && error_msg "msg_1() no param"
+    echo
+    echo "====  $1  ===="
+}
+
+msg_2() {
+    [ -z "$1" ] && error_msg "msg_2() no param"
+    echo "---  $1   ---"
+}
+
+msg_3() {
+    [ -z "$1" ] && error_msg "msg_3() no param"
+    echo "-> $1"
+}
+
+
+is_ish() {
+    test -d /proc/ish
+}
+
+is_aok_kernel() {
+    grep -qi aok /proc/ish/version 2> /dev/null
+}
+
+openrc_might_trigger_errors() {
+    echo
+    echo "You might see a few errors printed as services are activated."
+    echo "The iSH family doesn't fully support openrc yet, but the important parts work!"
+    echo
+}
+
+
+
+build_status_set() {
+    if [ -z "$1" ]; then
+        error_msg "build_status_set() no param"
+    fi
+    mkdir -p "$BUILD_STATUS"
+    msg_3 "build_staus_set($1)"
+    touch "$BUILD_STATUS/$1"
+}
+
+build_status_get() {
+    #
+    # A second param prevents logging of status
+    #
+    if [ -z "$1" ]; then
+        error_msg "build_status_get() no param"
+    fi
+    test -f "$BUILD_STATUS/$1"
+    exitstatus="$?"
+    case "$exitstatus" in
+
+        0 ) status="True" ;;
+
+        *)  status="False" ;;
+
+    esac
+
+    [ -z "$2" ] && msg_3 "build_status_get($1) $status"
+    unset status
+    return "$exitstatus"
+}
+
+#  shellcheck disable=SC2120
+build_status_clear() {
+    msg_3 "build_status_clear($1)"
+    if [ -n "$1" ]; then
+        fname="$BUILD_STATUS/$1"
+        rm -f "$fname"
+        msg_3 "Cleared $fname"
+    fi
+    if [ "$(find "$BUILD_STATUS"/ 2>/dev/null |wc -l)" -le 1 ]; then
+        rm "$BUILD_STATUS" -rf
+        msg_3 "Cleared entire $BUILD_STATUS"
+    fi
+}
+
+
+
+#  shellcheck disable=SC2120
+select_profile() {
+    #
+    #  If param two is defined, the previous profile (profile.org)
+    #  will not be kept, in fact removed if present
+    #
+    replacement_profile="$1"
+    # if [ -n "$2" ]; then
+    #     keep_org=false
+    # else
+    #     keep_org=true
+    # fi
+    msg_2 "select_profile($replacement_profile)"
+    if [ -z "$replacement_profile" ]; then
+        error_msg "select_profile() - no param"
+    fi
+    msg_3 "Selecting profile: $replacement_profile"
+    cp -a "$replacement_profile" "$BUILD_ROOT_D"/etc/profile
+    chmod 744 "$BUILD_ROOT_D"/etc/profile
+    chown root: "$BUILD_ROOT_D"/etc/profile
+    # msg_3 "select_profile($replacement_profile)  done"
+ }
+
+run_additional_tasks_if_found() {
+    msg_2 "run_additional_tasks_if_found()"
+    if [ -x "$ADDITIONAL_TASKS_SCRIPT" ]; then
+        msg_1 "Running additional setup tasks"
+        "$ADDITIONAL_TASKS_SCRIPT" && rm "$ADDITIONAL_TASKS_SCRIPT"
+    else
+        msg_3 "No additional tasks to be run"
+    fi
+    # msg_2 "run_additional_tasks_if_found()  done"
+}
+
+
+#
+#  Detecting build environments
+#  0 = other, not able to chroot to complete image
+#  1 = iSH
+#  2 = Linux (x86)
+#
+if is_ish ; then
+    BUILD_ENV=1
+elif uname -a | grep -qi linux && uname -a | grep -q x86; then
+    BUILD_ENV=2
 else
-    #  shellcheck disable=SC1091
-    . /AOK/AOK_VARS || exit 1
+    BUILD_ENV=0  # chroot not possible
 fi
 
-# Shorthands for some directories
-BUILD_BASE_D="/tmp/AOK"
-BUILD_ROOT_D="$BUILD_BASE_D/iSH-AOK-FS"
+
+
+#
+#  Locations for "other" stuff
+#
+
+#  Where Alpine miniroot fs is cached
 MINIROOT_FS_CACHE_D="/tmp/Alpine_miniroot_fs_cache"
 
-# extract the release/branch/major version, gives something like 3.14
-ALPINE_RELEASE="$(echo "$ALPINE_VERSION" | cut -d"." -f 1,2)"
+#  Where Debian FS is cached
+DEBIAN_FS_CACHE_D="/tmp/Debian_fs_cache"
 
+# If this is run on an iSH node, the image is copied to this location
+ICLOUD_ARCHIVE_D="/iCloud/AOK_Archive"
+
+
+#
+#  Pre-generated image names
+#
 
 # mini-root fs to be downloaded and used
 MINIROOT_FS="alpine-minirootfs-${ALPINE_VERSION}-x86.tar.gz"
@@ -37,35 +199,117 @@ MINIROOT_FS="alpine-minirootfs-${ALPINE_VERSION}-x86.tar.gz"
 # image name for AOK builds
 AOK_FS="Alpine_${ALPINE_VERSION}-iSH-AOK_${AOK_VERSION}.tgz"
 
+# image name for downloaded Debian tar ball
+DEBIAN_FS="$(echo "$DEBIAN_TARBALL" | grep -oE '[^/]+$')"
+
+
 # image name for generic builds
 BASIC_FS="Alpine-${ALPINE_VERSION}-iSH.tgz"
 
 
-#  Where all aok content gets installed on destination FS
-#  to refer to this location from the build env, use $BUILD_ROOT_D/$AOK_CONTENT
-AOK_CONTENT="/AOK"
 
 #
-#  Either run this script chrooted if the host OS supports it, or run it
-#  inside iSH-AOK once it has booted this FS
+#  Statuses are files put in place in /etc/opt/AOK on the destination FS
+#  to indicate various states of progress
 #
-SETUP_AOK_FS="$AOK_CONTENT/aok_setup_fs"
 
-# If this is run on an iSH node, the image is copied to this location
-ICLOUD_ARCHIVE_D="/iCloud/AOK_Archive"
+#  Indicator this is an env being built
+STATUS_BEING_BUILT="env_beeing_built"
+#
+#  Select distro has been prepared, ie the prepare does not to be run during
+#  deploy
+#
+STATUS_SELECT_DISTRO_PREPARED="select_distro_prepared"
+#  This is chrooted
+STATUS_IS_CHROOTED="is_chrooted"
 
 #
-# Hint to iSH this is the first time booting. Checked for by
-# /usr/local/bin/post_boot.sh
+#  Hint to /profile that this was a pre-built FS, meaning /etc/profile should not
+#  wait for $FIRST_BOOT_NOT_DONE_HINT to disappear, and post_boot.sh should not
+#  run (from inittab) /etc/profile will
 #
-FIRST_BOOT_NOT_DONE_HINT="/etc/FIRSTBOOT"
+STATUS_PREBUILT_FS="prebuilt_fs_first_boot"
 
-ADDITIONAL_TASKS_SCRIPT="/etc/opt/additional_tasks"
+
+
+#
+#  temp value until we know if this is dest FS, so that BUILD_ROOT_D can be
+#  selected
+#
+BUILD_STATUS_RAW="/etc/opt/AOK"
+
+#
+#  STATUS_BEING_BUILT and BUILD_STATUS, used by build_status_get()
+#  must be defined before this
+#
+if build_status_get "$STATUS_IS_CHROOTED" ; then
+    BUILD_ROOT_D=""
+    msg_1 "This is chrooted"
+elif test -f "$BUILD_STATUS_RAW/$STATUS_BEING_BUILT" ; then
+    BUILD_ROOT_D=""
+    msg_1 "This is running on dest platform"
+else
+    msg_1 "Not chrooted, not dest platform"
+    BUILD_ROOT_D="$BUILD_BASE_D/iSH-AOK-FS"
+fi
+
+
+#  Now the proper value can be set
+BUILD_STATUS="${BUILD_ROOT_D}${BUILD_STATUS_RAW}"
+
+
+#  Placeholder, to store  what version of AOK that was used
+FILE_AOK_RELEASE="$BUILD_ROOT_D"/etc/aok-release
+
+#  Placeholder, only used for Alpine deploys
+FILE_ALPINE_RELEASE="$BUILD_ROOT_D"/etc/alpine-release
+
+
 #
 #  How long the introduction should be displayed when the system is setup
 #  during first boot
 #
 FIRST_BOOT_INTRODUCTION_DISPLAY_TIME=15
+
+
+
+#
+#  Alpine related build env
+#
+
+#
+#  Extract the release/branch/major version, from the requested Alpine,
+#  gives something like 3.14
+ALPINE_RELEASE="$(echo "$ALPINE_VERSION" | cut -d"." -f 1,2)"
+
+#
+#  Either run this script chrooted if the host OS supports it, or run it
+#  inside iSH-AOK once it has booted this FS
+#
+SETUP_ALPINE_FS="$AOK_CONTENT"/Alpine/setup_alpine.sh
+SETUP_ALPINE_FINAL="$AOK_CONTENT"/Alpine/setup_alpine_final_tasks.sh
+SETUP_DEBIAN="$AOK_CONTENT"/Debian/setup_debian.sh
+SETUP_COMMON_AOK="$AOK_CONTENT"/common_AOK/setup_common_env.sh
+SETUP_CHOOSE_DISTRO_PREPARE="$AOK_CONTENT"/choose_distro/select_distro-prepare.sh
+
+
+#
+#  First boot additional tasks to be run, defined in AOK_VARS,
+#  FIRST_BOOT_ADDITIONAL_TASKS
+#
+ADDITIONAL_TASKS_SCRIPT="$BUILD_ROOT_D/opt/additional_tasks"
+
+
+#
+#  First profiles used during 1st boot to finalize setup
+#  Lastly the final profiles, depending on Distribution
+#
+PROFILE_ALPINE_PRE_BUILT="$AOK_CONTENT"/Alpine/etc/profile.prebuilt-FS
+PROFILE_ALPINE_DEPLOY_ON_DEST="$AOK_CONTENT"/Alpine/etc/profile.build_on_dest
+PROFILE_CHOOSE_DISTRO="$AOK_CONTENT"/choose_distro/etc/profile.select_distro
+PROFILE_ALPINE="$AOK_CONTENT"/Alpine/etc/profile
+PROFILE_DEBIAN="$AOK_CONTENT"/Debian/etc/profile
+PROFILE_DEBIAN_COMPLETE_DEPLOY="$AOK_CONTENT"/Debian/etc/profile.finish_setup
 
 
 #
@@ -77,33 +321,14 @@ LOGIN_ORIGINAL="/bin/login.alpine"
 
 
 #
-#  Detecting build environments
-#  0 = other, not able to chroot to complete image
-#  1 = iSH
-#  2 = Linux (x86)
+#  Local overrides, ignored by git. They will be appended to BUILD_ENV
+#  if found. This is intended for debuging and testing, since stuff
+#  found will be appended to this file on the destination.
+#  Produciton changes should go here, and such releases should be
+#  built without the asociated dot-files.
 #
-if [ -d "/proc/ish" ]; then
-    build_env=1
-elif uname -a | grep -qi linux && uname -a | grep -q x86; then
-    build_env=2
-else
-    build_env=0  # chroot not possible
-fi
+local_overrides="$AOK_CONTENT/.BUILD_ENV"
 
-
-is_aok_kernel() {
-    grep -qi aok /proc/ish/version 2> /dev/null
-    return $?
-}
-
-run_additional_tasks_if_found() {
-    if [ -n "$ADDITIONAL_TASKS_SCRIPT" ]; then
-        if [ -x "$ADDITIONAL_TASKS_SCRIPT" ]; then
-            echo
-            echo "Running additional setup tasks"
-            echo
-            $ADDITIONAL_TASKS_SCRIPT
-            rm "$ADDITIONAL_TASKS_SCRIPT"
-        fi
-    fi
-}
+#  shellcheck disable=SC1090
+[ -f "$local_overrides" ] && . "$local_overrides"
+unset local_overrides
diff --git a/build_fs b/build_fs
--- a/build_fs
+++ b/build_fs
@@ -1,4 +1,5 @@
 #!/bin/sh
+#  shellcheck disable=SC2154
 #
 #  Part of https://github.com/emkey1/AOK-Filesystem-Tools
 #
@@ -9,33 +10,31 @@
 #  Primary purpose is to create iSH-AOK file systems, but can also be used
 #  to create bare-bones Alpine-Linux file systems.
 #
-version="1.3.5"
-
+version="2.0.0-a"
 
 #  shellcheck disable=SC1007
-fs_build_d=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
 prog_name=$(basename "$0")
 
+#  shellcheck disable=SC1091
+. /opt/AOK/BUILD_ENV
+
 
 #
-#  Ensure this is run in the intended location in case this was launched from
-#  somewhere else.
+#  Point to AOK-Filesystem-Tools dir, in case this was run with a path
 #
-cd "$fs_build_d" || exit 1
+#  shellcheck disable=SC1007
+cd "$AOK_CONTENT" || exit 1
 
-# Read in vars
-# shellcheck disable=SC1091
-. ./BUILD_ENV
+build_debian_FS=false            # true means build Debian FS
+distro_select=false        # true means choose between Alpine and Debian
+pre_build_FS=false         # true meand generat4 pre-built FS
+aok_FS_do_compress=true    # compress FS at end of build_fs
+FS_compress_verbose=false  # Do tar -v
 
-aok_FS_mods=false
-skip_AOK_Files=false
-aok_FS_do_compress=true
-FS_compress_verbose=false
-
-aok_files="$BUILD_ROOT_D/$AOK_CONTENT"
+aok_files="${BUILD_ROOT_D}${AOK_CONTENT}"
 
 
-show_help() {
+show_help() {  # Multi OK 1
     cat <<EOF
 $prog_name, version $version
 
@@ -51,6 +50,8 @@ Available options:
 
 -h  --help         Print this help and exit.
 -v  --version      Show version and exit.
+-s  --select       Offer selection between Alpine & Debian on first boot.
+-d  --debian       Build a Debian FS.
 -p  --prebuilt     Build the entire FS on the running platform, making for quicker
                    imports on target device, but 10 times larger image files.
                    This can only be done on iSH or Linux (x86)!
@@ -59,16 +60,15 @@ Available options:
                    Instructions about this procedure and howto then complete
                    the build once done will be displayed at the end of the build.
 -z  --zip-progress Display progrss as FS is being compressed.
--u                 Create an unmodified FS, don't even copy $AOK_CONTENT
 EOF
     exit 0
 }
 
-show_version() {
+show_version() {  # Multi OK 1
     echo "$prog_name $version"
 }
 
-parse_arguments() {
+parse_arguments() {  # Multi OK 1
     while [ -n "$1" ]; do
 
         case "$1" in
@@ -77,6 +77,29 @@ parse_arguments() {
 
             "-v" | "-V" | "--version" ) show_version ; exit 0 ;;
 
+            "-d" | "--debian" )
+                build_debian_FS=true
+                shift
+                ;;
+
+            "-s" | "--select" )
+                if $pre_build_FS ; then
+                    echo "-p and -d can not be combined!"
+                    exit 1
+                fi
+                distro_select=true
+                shift
+                ;;
+
+            "-p" | "--prebuilt" )
+                if $distro_select ; then
+                    echo "-p and -d can not be combined!"
+                    exit 1
+                fi
+                pre_build_FS=true
+                shift
+                ;;
+
             "-c" |  "--no_compress" )
                 aok_FS_do_compress=false
                 shift
@@ -84,17 +107,6 @@ parse_arguments() {
 
             "-z" | "--zip-progress" )
                 FS_compress_verbose=true
-                shift
-                ;;
-
-            "-p" | "--prebuilt" )
-                aok_FS_mods=true
-                shift
-                ;;
-
-            "-u" )
-                skip_AOK_Files=true
-                aok_FS_mods=false
                 shift
                 ;;
 
@@ -107,40 +119,36 @@ parse_arguments() {
     done
 }
 
-display_build_env() {
+display_build_env() {  # Multi OK 1
     #
     #  Displaying build environment
     #
-    [ "$build_env" -eq 1 ] && run_mode="Building on iSH"
-    [ "$build_env" -eq 2 ] && run_mode="Building on x86 Linux"
+    [ "$BUILD_ENV" -eq 1 ] && run_mode="Building on iSH"
+    [ "$BUILD_ENV" -eq 2 ] && run_mode="Building on x86 Linux"
 
-    if ! $aok_FS_mods ; then
+    if ! $pre_build_FS ; then
         run_mode="Will not chroot"
-        if $skip_AOK_Files; then
-            run_mode="$run_mode, will not copy $AOK_CONTENT files"
-        else
-            run_mode="$run_mode, $AOK_CONTENT files will be copied"
-        fi
-    elif [ "$build_env" -eq 0 ]; then
+        run_mode="$run_mode, $AOK_CONTENT files will be copied"
+    elif [ "$BUILD_ENV" -eq 0 ]; then
         echo "Unfortunately you can not chroot into the image on this device"
         echo "This is only supported on iSH and Linux(x86)"
         echo "You must build using -m or -M on this platform (try -h for help)"
         exit 1
     fi
-    echo "=====  Run mode: $run_mode  ====="
+    msg_1 "Run mode: $run_mode"
 
 
     if [ "$(whoami)" != "root" ]; then
         # Must come after help display, to avoid infinite loop
         "$0" -h
-        echo
-        echo "ERROR: This must be run as root or using sudo!"
-        exit 1
+        error_msg "This must be run as root or using sudo!"
     fi
 
 
-    if      mount | grep -q "$BUILD_ROOT_D" || \
-            [ "$(find "$BUILD_ROOT_D"/dev | wc -l)" -gt 1 ]; then
+    # if build_status_get "$STATUS_BEING_BUILT" ; then
+    #     error_msg "Can't build a new env whilst the current is being built!"
+    # fi
+    if [ -d "$BUILD_ROOT_D/dev" ] && [ "$(find "$BUILD_ROOT_D"/dev | wc -l)" -gt 1 ]; then
         echo "ERROR: Active chroot session detected!"
         echo "       If this is due to a crash or abort, you can clear it by running:"
         echo "         sudo ./tools/do_chroot.sh -c"
@@ -149,15 +157,15 @@ display_build_env() {
     fi
 
 
-    echo
-    echo "=====  Building a $ALPINE_RELEASE  filesystem  ====="
+    msg_1 "Building a $ALPINE_RELEASE  filesystem"
 
     if ! $aok_FS_do_compress ; then
-        echo "*** Will not create the compressed image! ***"
+        msg_2 "*** Will not create the compressed image! ***"
     fi
 }
 
-clear_build_env() {
+clear_build_env() {  # Multi OK 1
+    msg_2 "clear_build_env()"
     #
     # Clear build env
     #
@@ -167,9 +175,11 @@ clear_build_env() {
         echo
         exit 1
     fi
+    # msg_3 "clear_build_env() done"
 }
 
-cache_miniroot_fs() {
+cache_miniroot_fs() {  # Multi OK 1
+    msg_2 "cache_miniroot_fs()"
     #
     #  Create miniroot fs cache dir if not present, cd to it and if download
     #  miniroot fs if not cached
@@ -181,81 +191,149 @@ cache_miniroot_fs() {
 
     # Download the Alpine miniroot if we need to
     if [ ! -f "$MINIROOT_FS" ]; then
-        echo "Caching miniroot"
+        msg_3 "Caching miniroot tarball"
         wget "https://dl-cdn.alpinelinux.org/alpine/v$ALPINE_RELEASE/releases/x86/$MINIROOT_FS"
+    fi
+    # msg_3 "cache_miniroot_fs() done"
+}
+
+cache_Debian_fs() {
+    msg_2 "cache_Debian_fs()"
+    if [ ! -d "$DEBIAN_FS_CACHE_D" ]; then
+        mkdir -p "$DEBIAN_FS_CACHE_D"
+    fi
+    cd "$DEBIAN_FS_CACHE_D" || {
+        error_msg "Failed to cd to debian cache"
+    }
+
+    if [ ! -f "$DEBIAN_FS" ]; then
+        wget "$DEBIAN_TARBALL"
+    fi
+    # msg_3 "cache_Debian_fs() done"
+}
+
+integrate_overrides() {
+    conf_file="$1"
+    case "$conf_file" in
+
+        AOK_VARS | BUILD_ENV ) ;;
+
+        *)
+            echo "ERROR: integrate_overrides($conf_file) - bad param"
+            exit 1
+            ;;
+
+    esac
+
+    if [ -f "$AOK_CONTENT"/."$conf_file" ]; then
+        msg_3 "adding .$conf_file  into $conf_file on destination"
+        {
+            echo
+            echo "# ---   inherrited overrides   ---"
+            echo
+        } >> "$aok_files"/"$conf_file"
+        cat "$AOK_CONTENT"/."$conf_file" >> "$aok_files"/"$conf_file"
     fi
 }
 
-copy_AOK_to_fs() {
+
+copy_AOK_to_dest() {
     #
     #  Copy AOK content to destination
     #
+    msg_2 "copy_AOK_to_dest()"
 
-    cp -pR "$fs_build_d"/ "$aok_files"
-    #
-    #  Remove stuff that should not be there
-    #
-    rm -f  "$aok_files"/README.md
-    rm -f  "$aok_files"/TODO.md
-    rm -rf "$aok_files"/.git*
+    mkdir -p "$aok_files"
+    mkdir -p "$BUILD_ROOT_D"/etc/opt
+    build_status_set "$STATUS_BEING_BUILT"
 
-    # #
-    # #  Move the AOK stuff into /AOK
-    # #
-    # aok_files="$BUILD_ROOT_D/$AOK_CONTENT"
+    rsync -ah                                       \
+        --exclude=.git/                             \
+        --exclude=.gitignore                        \
+        --exclude=.gitmodules                       \
+        --exclude=.vscode/                          \
+        --exclude=.AOK_VARS                         \
+        --exclude=.BUILD_ENV                        \
+        "$AOK_CONTENT" "$BUILD_ROOT_D"/opt
 
-    # mkdir "$aok_files"
-
-    # mv "$BUILD_ROOT_D"/BUILD_ENV         "$aok_files"
-    # mv "$BUILD_ROOT_D"/AOK_VARS          "$aok_files"
-
-    # mv "$BUILD_ROOT_D"/build_fs          "$aok_files"
-    # mv "$BUILD_ROOT_D"/aok_setup_fs      "$aok_files"
-    # mv "$BUILD_ROOT_D"/compress_image    "$aok_files"
-    # mv "$BUILD_ROOT_D"/LICENSE           "$aok_files"
-    # mv "$BUILD_ROOT_D"/Files             "$aok_files"
-    # mv "$BUILD_ROOT_D"/Docs              "$aok_files"
-    # mv "$BUILD_ROOT_D"/tools             "$aok_files"
+    integrate_overrides AOK_VARS
+    integrate_overrides BUILD_ENV
 
     chown -R root: "$aok_files"
-
-    unset d_aok
+    # msg_3 "copy_AOK_to_dest() done"
 }
 
 add_additional_tasks_if_defined() {
     #
     #  If defined, append additional tasks
     #
-    mkdir -p "$BUILD_ROOT_D/etc/opt"
+    msg_2 "add_additional_tasks_if_defined($FIRST_BOOT_ADDITIONAL_TASKS)"
     if [ -n "$FIRST_BOOT_ADDITIONAL_TASKS" ]; then
+        msg_3 "Creating additional tasks script"
+        add_task_dest="$BUILD_ROOT_D"/opt
+        mkdir -p "$add_task_dest"
         {
             echo "#!/bin/sh"
             echo "$FIRST_BOOT_ADDITIONAL_TASKS"
-        }  > "$BUILD_ROOT_D/$ADDITIONAL_TASKS_SCRIPT"
-        chmod 755 "$BUILD_ROOT_D/$ADDITIONAL_TASKS_SCRIPT"
-        echo "---  setup FIRST_BOOT_ADDITIONAL_TASKS to be run in $ADDITIONAL_TASKS_SCRIPT  ---"
+        }  > "$ADDITIONAL_TASKS_SCRIPT"
+        chmod 755 "$ADDITIONAL_TASKS_SCRIPT"
+        msg_2 "setup FIRST_BOOT_ADDITIONAL_TASKS to be run in $ADDITIONAL_TASKS_SCRIPT"
     fi
+    # msg_3 "add_additional_tasks_if_defined() done"
 }
 
-first_boot_fbat() {
-    echo "---  first_boot_fbat()   ---"
-    [ -z "$FIRST_BOOT_ADDITIONAL_TASKS" ] && return
-    #
-    #  Only set up a custom first boot handler, if there were user defined
-    #  tasks to be run.
-    #
+chroot_if_possible() {
+    action="$1"
+    [ -z "$action" ] && error_msg "chroot_if_possible() no param"
+    if [ "$BUILD_ENV" -gt 0 ]; then
+        msg_3 "chrooting: $action"
+        if ! "$AOK_CONTENT"/tools/do_chroot.sh "$action"; then
+            error_msg "in chroot, aborting build!"
+        fi
+    else
+        error_msg "Could not chroot, did not run: $action"
+    fi
 
-    #  /etc/profile will be restored just before the additional tasks
-    #  are run, this saves it to a in this context known name
-    mv "$BUILD_ROOT_D"/etc/profile "$BUILD_ROOT_D"/etc/profile.real
-
-    cp "$fs_build_d"/Files/profile.fbat "$BUILD_ROOT_D"/etc/profile
 }
 
-first_boot_aok_complete() {
-    echo "---  first_boot_aok_complete()   ---"
-    cp "$aok_files"/Files/profile.aok-complete "$BUILD_ROOT_D"/etc/profile
-    echo "---  custom /etc/profile forcing aok_setup_fs to be run on first boot  ---"
+setup_Alpine_in_advance() {
+    msg_2 "setup_Alpine_in_advance()"
+    mkdir -p /etc/opt
+
+    #  Indicate this FS is pre-built
+    build_status_set "$STATUS_PREBUILT_FS"
+
+    #
+    # chrooting and doing setup
+    #
+    if ! "$AOK_CONTENT"/tools/do_chroot.sh "$SETUP_ALPINE_FS"; then
+        error_msg "in chroot, aborting build!"
+    fi
+
+    select_profile "$PROFILE_ALPINE_PRE_BUILT"
+}
+
+setup_Alpine_on_1st_boot() {
+    msg_2 "setup_Alpine_on_1st_boot()"
+    # by setting this as the first of two, this will become the default profile
+    # when install is completed
+    select_profile "$PROFILE_ALPINE_DEPLOY_ON_DEST"
+}
+
+setup_Debian() {
+    msg_2 "setup_Debian()"
+    "$SETUP_DEBIAN"
+}
+
+select_distro_on_1st_boot() {
+    msg_2 "select_distro_on_1st_boot()"
+    msg_1 "Preparing for distro selections"
+    chroot_if_possible "$SETUP_CHOOSE_DISTRO_PREPARE"
+
+    # If Alpine is selected profile.org will be the intended, in case
+    # the build procedures get lost
+    select_profile "$PROFILE_CHOOSE_DISTRO"
+    # msg_3 "select_distro_on_1st_boot()  done"
 }
 
 
@@ -270,81 +348,93 @@ parse_arguments "$@"
 
 display_build_env
 
-echo
-echo "---  Preparing build environment  ---"
+msg_2 "Preparing build environment"
 
 clear_build_env
-cache_miniroot_fs
 
-echo "---  Create $BUILD_ROOT_D, copy minirootfs  ---"
-mkdir -p "$BUILD_ROOT_D"
-
-cd "$BUILD_ROOT_D" || exit 1
-tar xfz "$MINIROOT_FS_CACHE_D"/"$MINIROOT_FS"
-
-if $skip_AOK_Files ; then
-    echo "---  Purging all $AOK_CONTENT content from the new filesystem  ---"
-    first_boot_fbat
+if $build_debian_FS ; then
+    msg_2 "Create $BUILD_ROOT_D, copy Debian FS"
+    cache_Debian_fs
+    mkdir -p "$BUILD_ROOT_D"
+    cd "$BUILD_ROOT_D" || exit 1
+    msg_2 "Extracting Debian tarball"
+    tar xfj "$DEBIAN_FS_CACHE_D/$DEBIAN_FS" || {
+        echo "ERROR: Failed to untar Debian-fs"
+        echo
+        echo "Try to remove the cached file and run this again"
+        echo "$DEBIAN_FS_CACHE_D/$DEBIAN_FS"
+        exit 1
+    }
 else
-    copy_AOK_to_fs
-    echo "---  Stored $AOK_CONTENT on new filesystem  ---"
-
-    if ! $aok_FS_mods ; then
-        first_boot_aok_complete
-    fi
+    msg_2 "Create $BUILD_ROOT_D, copy minirootfs"
+    cache_miniroot_fs
+    mkdir -p "$BUILD_ROOT_D"
+    cd "$BUILD_ROOT_D" || exit 1
+    tar xfz "$MINIROOT_FS_CACHE_D"/"$MINIROOT_FS" || {
+        echo "ERROR: Failed to untar root-fs"
+        echo
+        echo "Try to remove the cached file and run this again"
+        echo "$MINIROOT_FS_CACHE_D/$MINIROOT_FS"
+        exit 1
+    }
 fi
 
-
-#
-#  Alpine initial motd suggests running setup-alpine. Not available on iSH
-#  Since aok_setup_fs will create an AOK relevant motd, deleting the default
-#  one makes sence.
-#
-rm "$BUILD_ROOT_D"/etc/motd
-echo "---  removed initial /etc/motd from new filesystem  ---"
-
-
-# Should always happen
-echo "---  created directory /iCloud inside new filesystem   ---"
-mkdir "$BUILD_ROOT_D"/iCloud
-
+copy_AOK_to_dest
+msg_2 "Stored $AOK_CONTENT on new filesystem"
 
 add_additional_tasks_if_defined
 
-if $aok_FS_mods ; then
-    #
-    # chrooting and doing setup
-    #
-    # We need a valid resolv.conf for the chrooted env to be able to do networking
-    cp /etc/resolv.conf "$BUILD_ROOT_D/etc"
-    echo "---  copied host /etc/resolve.conf to new filesystem  ---"
-
-    # dedicated chroot app
-    #if ! "$fs_build_d"/tools/do_chroot.sh "$SETUP_AOK_FS"; then
-    if ! "$fs_build_d"/tools/do_chroot.sh "$SETUP_AOK_FS"; then
-        echo "ERROR in chroot, aborting build!"
-        exit 1
-    fi
+if $pre_build_FS ; then
+    setup_Alpine_in_advance
+elif $build_debian_FS ; then
+    select_profile "$PROFILE_DEBIAN_COMPLETE_DEPLOY"
+elif $distro_select ;  then
+    select_distro_on_1st_boot
+else
+    setup_Alpine_on_1st_boot
 fi
+#
+#  Alpine initial motd suggests running setup-alpine. Not available on iSH
+#  Since SETUP_ALPINE_FS will create an AOK relevant motd,
+#  deleting the default one makes sence.
+#
+rm "$BUILD_ROOT_D"/etc/motd
+msg_2 "removed initial /etc/motd from new filesystem"
 
 
-echo
-echo "=====  The filesystem is ready!  ====="
-echo
+# Should always happen
+msg_2 "created directory /iCloud inside new filesystem"
+mkdir "$BUILD_ROOT_D"/iCloud
 
+
+msg_1 "The filesystem is ready!"
+
+#
+#  Consider to generate a tarball
+#
 if $aok_FS_do_compress ; then
     if $FS_compress_verbose ; then
         verbose="-z"
     else
         verbose=""
     fi
-    if ! "$fs_build_d"/compress_image "$verbose"; then
-        echo "ERROR detected in compress_image"
-        exit 1
+
+    if $build_debian_FS ; then
+        label="-l Debian-ish-AOK-$AOK_VERSION"
+    elif $distro_select ; then
+        #  shellcheck disable=SC2154
+        label="-l SelectDistro-$AOK_VERSION"
+    else
+        label=""
+    fi
+
+    #  shellcheck disable=SC2086
+    if ! "$AOK_CONTENT"/compress_image $label "$verbose"; then
+        error_msg "detected in compress_image"
     fi
 else
-    if [ "$build_env" -gt 0 ]; then
-        if $aok_FS_mods ; then
+    if [ "$BUILD_ENV" -gt 0 ]; then
+        if $pre_build_FS ; then
             set_shell=""
         else
             set_shell="/bin/ash"
@@ -359,7 +449,7 @@ else
     echo
     echo "This creates the compressed image that can be imported into AOK/iSH."
 
-    if [ "$build_env" -gt 0 ]; then
+    if [ "$BUILD_ENV" -gt 0 ]; then
         echo "You can revisit the filesystem by doing the above do_chroot and then"
         echo "compress_image again, in case you need to do further tweaks."
         echo "Running build again will erase the current iSH filesystem and create"
diff --git a/compress_image b/compress_image
--- a/compress_image
+++ b/compress_image
@@ -1,28 +1,25 @@
 #!/bin/sh
+# shellcheck disable=SC2154
 #
 #  Part of https://github.com/emkey1/AOK-Filesystem-Tools
 #
 #  License: MIT
 #
+#  Copyright (c) 2022: Jacob.Lundqvist@gmail.com
 #
 #  Compresses a FS into a tar file that can be mounted by iSH
 #
-version="1.3.4"
+version="1.3.5"
 
-#  shellcheck disable=SC1007
-fs_build_d=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
 prog_name=$(basename "$0")
 
-#
-#  Ensure this is run in the intended location in case this was launched from
-#  somewhere else.
-#
-cd "$fs_build_d" || exit 1
 
+#
+#  Point to AOK-Filesystem-Tools dir, in case this was run with a path
+#
+#  shellcheck disable=SC1091
+. /opt/AOK/BUILD_ENV
 
-# Read in vars
-# shellcheck disable=SC1091
-. ./BUILD_ENV
 
 
 FS_compress_verbose=false
@@ -39,6 +36,7 @@ Available options:
 
 -h  --help         Print this help and exit.
 -v  --version      Show version and exit.
+-l  --label        Provide a name for tarball (without extension)
 -z  --zip-progress Display progrss as FS is being compressed.
 EOF
     exit 0
@@ -57,105 +55,99 @@ while [ -n "$1" ]; do
 
         "-v" | "-V" | "--version" ) show_version ; exit 0 ;;
 
+        "-l" | "--label" )
+            shift
+            tar_name="$1"
+            if [ -z "$tar_name" ]; then
+                echo "ERROR: label needs name as additional param!"
+                exit 1
+            fi
+            ;;
+
         "-z" | "--zip-progress" )
             FS_compress_verbose=true
-            shift
             ;;
 
         *)
-            echo "ERROR: bad param, try -h"
-            exit 1
+            error_msg "bad param, try -h"
             ;;
     esac
+    shift
 
 done
-
 
 
 if [ "$(whoami)" != "root" ]; then
     # Must come after help display, to avoid infinite loop
     "$0" -h
-    echo
-    echo "ERROR: This must be run as root or using sudo!"
-    exit 1
+
+    error_msg "This must be run as root or using sudo!"
 fi
 
 if [ ! -d "$BUILD_ROOT_D" ]; then
-    echo "ERROR: No image built yet, [$BUILD_ROOT_D]!"
-    exit 1
+    error_msg "No image built yet, [$BUILD_ROOT_D]!"
 fi
 
 if [ "$(find "$BUILD_ROOT_D"/dev | wc -l)" -gt 1 ]; then
-    echo "ERROR: Active chroot session detected!"
-    exit 1
+    error_msg "Active chroot session detected!"
 fi
 
-if [ -d "$BUILD_ROOT_D"/AOK ]; then
-    tgz_file="$AOK_FS"
-    uses_aok=true
+if [ -z "$tar_name" ]; then
+    tar_ball="$AOK_FS"
 else
-    tgz_file="$BASIC_FS"
-    uses_aok=false
+    tar_ball="${tar_name}.tgz"
 fi
 
-if $uses_aok; then
-    hint_first_boot="$BUILD_ROOT_D/$FIRST_BOOT_NOT_DONE_HINT"
-    if [ -d "$BUILD_ROOT_D/$AOK_CONTENT" ]; then
-        #
-        #  Tell iSH to run first boot tasks
-        #
-        touch "$hint_first_boot"
-    fi
-fi
+
+# set location
+tar_ball="$BUILD_BASE_D/$tar_ball"
 
 
 # echo "removing temp /dev items"
 # rm  -f "$BUILD_ROOT_D"/dev/*
 
-echo "=====  Creating image  ====="
-echo
+msg_1 "Creating image"
 
 #
 # Tar up and zip the result
 #
-cd "$BUILD_ROOT_D" || exit 1
+cd "$BUILD_ROOT_D" || exit 99
 
 if $FS_compress_verbose ; then
     opts='cvf'
 else
     opts='cf'
 
-    echo "Compressing the image on an iSH node will take around 12 minutes to complete"
-    echo "The same done even on a modest Linux node will take around 30 seconds"
-    echo
+
+    if grep -q AOK_COMPLETION_ON_TARGET "$BUILD_ROOT_D"/etc/profile; then
+        #
+        #  This is a pre-built image, so fairly large, give a hint about
+        #  expected compress time
+        #
+        echo "Compressing a pre-built image on an iSH node will take around 12 minutes to complete"
+        echo "The same done even on a modest Linux node will take around 30 seconds"
+        echo
+    fi
     echo "In order not to have to wait so long without any indication anything is"
     echo "happening,  you can use the option -z when running build_fs or compress_image."
     echo "This will give a detailed progress report as each file is packed."
 fi
 
 
-tar "$opts" - . | gzip -9 > "../$tgz_file"
+tar "$opts" "$tar_ball" .
 
 #
 # copy it to /iCloud if this runs on iSH
 #
-if [ "$build_env" -eq 1 ]; then
-    echo "---  Copying image into $ICLOUD_ARCHIVE_D  ---"
+if is_ish ; then
+    msg_2 "Copying image into $ICLOUD_ARCHIVE_D"
     mkdir -p "$ICLOUD_ARCHIVE_D"
-    cp "$BUILD_BASE_D/$tgz_file" "$ICLOUD_ARCHIVE_D"
+    cp "$tar_ball" "$ICLOUD_ARCHIVE_D"
 fi
 echo
 
 
-echo "=====  Image is ready: $BUILD_BASE_D/$tgz_file  ====="
-echo
+msg_1 "Image is ready: $tar_ball"
 
-
-if $uses_aok; then
-    #
-    #  Remove first boot hint, in order to make chroot bash -l possible
-    #
-    [ -e "$hint_first_boot" ] && rm "$hint_first_boot"
-fi
 
 exit 0 #  Avoid exiting with error if above file did not exist
