Displays error if not in /opt/AOK

diff --git a/compress_image b/compress_image
--- a/compress_image
+++ b/compress_image
@@ -34,6 +34,17 @@ EOF
 #===============================================================
 
 #
+#  Ensure this is run in the intended location in case this was launched from
+#  somewhere else.
+#
+cd /opt/AOK || {
+    echo
+    echo "ERROR: The AOK file tools needs to be saved to /opt/AOK for things to work!".
+    echo
+    exit 1
+}
+
+#
 #  Point to AOK-Filesystem-Tools dir, in case this was run with a path
 #
 #  shellcheck disable=SC1091
