further cleanup of login setup

diff --git a/setup_image_chrooted b/setup_image_chrooted
--- a/setup_image_chrooted
+++ b/setup_image_chrooted
@@ -244,6 +244,14 @@ else
 	esac
 fi
 
+#
+#  Extra sanity check, only continue if there is a runable /bin/login
+#
+if [ ! -x /bin/login ]; then
+	echo "ERROR: no /bin/login present!"
+	exit 1
+fi
+
 
 echo "---  Enabling openrc  ---"
 
