service as shellscript works

diff --git a/common_AOK/etc/init.d/runbg b/common_AOK/etc/init.d/runbg
--- a/common_AOK/etc/init.d/runbg
+++ b/common_AOK/etc/init.d/runbg
@@ -1,71 +1,65 @@
-#!/sbin/openrc-run
+#! /bin/sh
 #
-#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
-#
-#  License: MIT
-#
-#  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
+# Copyright (c) 2021: Jacob.Lundqvist@gmail.com 2021-12-29
+# License: MIT
 #
 
 ### BEGIN INIT INFO
 # Provides:          runbg
-# Required-Start:    $local_fs 
-# Required-Stop:     $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Polls GPS to allow iSH to run in background
-# Description:       By monitoring GPS, iOS allows apps to continue to run in
-#                    the background. However there is no guarantee,
-#                    If resources run low, backgrounded apps will be
-#                    suspended, only resuming when put in foreground again.
+# Short-Description: Reads GPS to ensure iSH continues to run when in background
+# Description:       Reads GPS to ensure iSH continues to run
+#                    when in background.
 ### END INIT INFO
-#
-#  This service reads the GPS and discards the output to /dev/null.
-#  So this is not tracking you in any way. The sole purpose of this
-#  is that this is the only way to ensure an iOS program continues to run
-#  in the background.
-#  This process has no noticeable impact on battery life.
-#
-
-name="run in background"
-description="Reads GPS to ensure iSH continues to run when in background"
-
-command="/bin/cat"
-command_args="/dev/location > /dev/null"
-command_background="YES"
-
-pidfile="/run/runbg.pid"
 
 
-#
-#  The above is all that is needed to have cat /dev/location > /dev/null
-#  run as a simple daemon with pid being monitored.
-#
-#  The below parts are just adding some additional sanity, not needed
-#  in order for the daemon to work by itself.
-#
-#  Pointless to have more than one thing doing this.
-#  The below aborts with error if:  cat /dev/location
-#  is already running.
-#  And displays warning if other processes are detected
-#  after stoping.
-#
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="ensure iSH runs in background"
+NAME=runbg
+
+DAEMON="/usr/bin/cat"
+DAEMON_ARGS="/dev/location > /dev/null"
+PIDFILE=/run/${NAME}.pid
+
+SCRIPTNAME=/etc/init.d/$NAME
+
+
+# Define LSB log_* functions.
+. /lib/lsb/init-functions
+
+
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   other if daemon could not be started or a failure occured
+	start-stop-daemon --start --quiet  --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
+}
+
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   other if daemon could not be stopped or a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
+}
+
+
 
 check_for_other_polling() {
-    #  Argh Alpine (BusyBox) displays pid,user instead of user,pid
-    if [ -f /etc/alpine-release ]; then
-        ps_cmd="ps axu -o user,pid,args"
-    else
-        ps_cmd="ps axu"
-    fi
-    other_pids="$($ps_cmd | grep /dev/location | grep -v grep | awk '{ print $2 }' |  tr '\n' ' ')"
+    other_pids=$(ps |grep "cat /dev/location" | grep -v grep | awk '{ print $1 }' |  tr '\n' ' ')
 }
 
 
 start_pre() {
     check_for_other_polling
     if [ "$other_pids" != "" ]; then
-	eerror "ERROR: Other processes polling GPS [ $other_pids]"
+	    echo "ERROR: Other processes polling GPS [ $other_pids]"
+        log_end_msg 1
    fi
 }
 
@@ -73,6 +67,53 @@ start_pre() {
 stop_post() {
     check_for_other_polling
     if [ "$other_pids" != "" ]; then
-	ewarn "WARNING: Other processes polling GPS [ $other_pids]"
+	    echo "WARNING: Other processes polling GPS [ $other_pids]"
+        log_end_msg 1
    fi
 }
+
+
+case "$1" in
+  start)
+	log_daemon_msg "Starting $DESC" "$NAME"
+	# start_pre
+	do_start
+	case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_progress_msg "already started"
+		   log_end_msg 0 ;;
+		*) log_end_msg 1 ;;
+	esac
+
+	;;
+  stop)
+	log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+
+		0)  # stop_post
+		    log_end_msg 0
+		    ;;
+
+		1) log_progress_msg "already stopped"
+		   log_end_msg 0 ;;
+		*) log_end_msg 1 ;;
+	esac
+	;;
+  restart|force-reload)
+	$0 stop
+	$0 start
+	;;
+  try-restart)
+	$0 status >/dev/null 2>&1 && $0 restart
+	;;
+  status)
+	status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
+	;;
+  *)
+	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|try-restart|status}" >&2
+	exit 3
+	;;
+esac
+
+:
