major cleanup

diff --git a/common_AOK/usr_local_sbin/fix_dev b/common_AOK/usr_local_sbin/fix_dev
--- a/common_AOK/usr_local_sbin/fix_dev
+++ b/common_AOK/usr_local_sbin/fix_dev
@@ -6,41 +6,99 @@
 #
 #  Copyright (c) 2023: Jacob.Lundqvist@gmail.com
 #
-#  Fixes /dev entries in one go, suitable for cut-paste
+#  Ensures iSH /dev entries are good
+#
+#  Normally this will refuse to run if not started from init.
+#  During setup, when this isnt in inittab yet, this check can be
+#  ignored with the param: >> ignore_init_check <<
+#
+#  This allows a deploy script to run fix_dev in order to ensure no
+#  device weirdness is pressent
 #
 
-log_file="/var/log/fix_dev.log"
-
 log_it() {
+    #
+    #  param 2 indicates this should also be printed, if it is > -1
+    #  it will be used as an exit code
+    #
     echo "[$(date)] $1" >>"$log_file"
-    
+
     if [ -n "$2" ]; then
         echo "$1"
-        exit "$2"
+        if [ "$2" -gt -1 ]; then
+            clear_pidfile
+            exit "$2"
+        fi
     fi
 }
 
+clear_pidfile() {
+    rm -f "$pid_file"
+}
 
-
-is_ish() {
+this_is_ish() {
     test -d /proc/ish
 }
 
+is_char_dev() {
+    _d="$1"
+    if [ -z "$_d" ]; then
+        log_it "ERROR: is_char_dev() - called without param!" -1
+        return 1
+    elif [ ! -e "$_d" ]; then
+        log_it "ERROR: is_char_dev($_d) - dev does not exist!" -1
+        return 1
+    fi
+
+    #  Return status
+    if [ -c "$_d" ]; then
+        # log_it "ok_dev: $_d" -1
+        return 0
+    else
+        log_it "WARNING: $_d seems wrong, will try to again!" -1
+        log_it "$(ls -l "$_d")" -1
+        return 1
+    fi
+}
+
+#===============================================================
+#
+#   Main
+#
+#===============================================================
+
+log_file="/var/log/fix_dev.log"
+
+#
+#  When pressent fix_dev is running, so other processes during early
+#  startup should hold whilst this exists
+#
+pid_file="/run/fixdev.pid"
+
+#
+#  This should only run from init, so it is safe to ignore any previous
+#  content in the pidfile
+#
+echo "$$" >"$pid_file"
+
+if ! this_is_ish; then
+    log_it "WARNING: Not iSH kernel, skipping fix_dev" 0
+fi
 if [ "$(uname)" = "Darwin" ]; then
     log_it "Don't run this on MacOS!!" 1
 fi
 
-if ! is_ish; then
-    log_it "ERROR: Not iSH kernel, skipping fix_dev" 0
+#  shellcheck disable=SC2154
+if [ -e /etc/opt/AOK/this_fs_is_chrooted ]; then
+    log_it "WARNING: chrooted, Skipping fix_dev" 0
 fi
 
-#  shellcheck disable=SC2154
-if [ -e /etc/opt/AOK/is_chrooted ]; then
-    log_it "WARN: Skipping fix_dev when chrooted" 0
+if [ "$1" != "ignore_init_check" ]; then
+    [ "$PPID" -gt 1 ] && log_it "ERROR: Not started from init, parent is ($PPID) exiting" 1
 fi
 
 while true; do
-    log_it "fixing devs"
+    log_it "fixing devs" -1
     # parenthesis, so this can be copy pasted into a single action
     (
         rm -f /dev/null && mknod -m 666 /dev/null c 1 3
@@ -55,14 +113,15 @@ while true; do
         rm -f /dev/clipboard && mknod -m 666 /dev/clipboard c 240 0
         rm -f /dev/location && mknod -m 666 /dev/location c 240 1
     )
-    #
-    #  hard to check every one, when fix_dev fails for me it tends to
-    #  leave /dev/null as a regular file, so perhaps this is enough?
-    #
-    [ -c /dev/null ] && break
 
-    log_it "$(ls -l /dev/null)"
-    log_it "WARN: /dev/null seems wrong, will try to again!"
+    is_char_dev /dev/null && is_char_dev /dev/zero &&
+        is_char_dev /dev/full && is_char_dev /dev/random &&
+        is_char_dev /dev/urandom && is_char_dev /dev/tty1 &&
+        is_char_dev /dev/tty && is_char_dev /dev/console &&
+        is_char_dev /dev/ptmx && is_char_dev /dev/clipboard &&
+        is_char_dev /dev/location && break
+
+    log_it "Some check failed, will try to fix devices again" -1
     sleep 1
 done
 
@@ -71,6 +130,7 @@ if [ ! -L /dev/fd ]; then
     ln -sf /proc/self/fd /dev/fd
 fi
 
-
 # Debug log
-log_it "fix_dev - done"
+log_it "fix_dev - done" -1
+
+clear_pidfile
