conformance to stricter shellcheck settings

diff --git a/Files/bin/aok_groups b/Files/bin/aok_groups
--- a/Files/bin/aok_groups
+++ b/Files/bin/aok_groups
@@ -61,6 +61,8 @@ check_for_option() {
             is_iSH=1
             ;;
 
+        *) ;;
+
     esac
 }
 
@@ -148,7 +150,7 @@ process_items() {
                         group_lst="${group_lst#* }"
 
                         g_len="${#g}"
-                        [ "$g_len" -gt $max_len ] && max_len="$g_len"
+                        [ "$g_len" -gt "$max_len" ] && max_len="$g_len"
 
                         [ "$group_lst" = "$g" ] && break  # list done
                     done
@@ -172,6 +174,11 @@ process_items() {
                     pkg_handling del
                     return
                 fi
+                ;;
+
+            *)
+                echo "ERROR: Unknown task: $task"
+                exit 1
                 ;;
 
         esac
