rewrite

diff --git a/Files/bin/elock b/Files/bin/elock
--- a/Files/bin/elock
+++ b/Files/bin/elock
@@ -1,55 +1,75 @@
-#!/bin/ash
+#!/bin/sh
 #
+#  Switch extra locking on or off
+#
+version="2.0.0  2022-05-25"
 
-# Switch extra locking on or off
+prog_name=$(basename "$0")
 
 
-if ! [[ -f /proc/ish/defaults/enable_extralocking ]]
-then 
-   echo "Not running on iSH-AOK, exiting."
-   exit 1;
+if ! [ -f /proc/ish/defaults/enable_extralocking ]; then
+    echo "Not running on iSH-AOK, exiting."
+    exit 1;
 fi
 
-WHO=`whoami`
 
 # execute again as root
-if [ "$WHO" != "root" ]; then
-     sudo /usr/local/bin/elock $1
-     exit 0
+if [ "$(whoami)" != "root" ]; then
+    sudo "$0" "$1"
+    exit 0
 fi
 
-function usage() {
-    echo
-    echo "Switch extra locking on or off."    
-    echo "Switching it on may improve stability but impacts performance"
-    echo
-    echo "elock <on|off|status>"
-    echo
-}
 
-if [[ -z $1 ]]; then 
-    usage
-    exit 1
-fi
-
-# Start options for special cases
-
-if [[ "$1" = "on" ]]; then 
-    echo "true" > /proc/ish/defaults/enable_extralocking
-    exit 0
-elif [[ "$1" = "off" ]]; then 
-    echo "false" > /proc/ish/defaults/enable_extralocking
-    exit 0
-elif [[ "$1" = "status" ]]; then 
-    STATE=`cat /proc/ish/defaults/enable_extralocking`
-    if [[ "$STATE" = "true" ]]; then 
+show_status() {
+    STATE="$(cat /proc/ish/defaults/enable_extralocking)"
+    if [ "$STATE" = "true" ]; then
         echo "on"
-    elif [[ "$STATE" = "false" ]]; then 
+    elif [ "$STATE" = "false" ]; then
         echo "off"
     fi
-    exit 0
-fi
+}
 
-echo "Unknown option $1"
 
-exit 1
+usage() {
+    echo "Version:  $version"
+    echo
+    echo "usage: $prog_name on | off | status"
+    echo
+    echo "Switch extra locking on or off."
+    echo "Switching it on may improve stability but impacts performance"
+    echo
+    printf "Current status: "
+    show_status
+}
+
+
+case "$1" in
+
+    "" | "-h" | "--help" )
+	usage
+	exit 0
+	;;
+
+    "on" )
+	echo "true" > /proc/ish/defaults/enable_extralocking
+	exit 0
+	;;
+
+    "off" )
+	echo "false" > /proc/ish/defaults/enable_extralocking
+	exit 0
+	;;
+
+    "status" )
+	show_status
+	exit 0
+	;;
+
+    * )
+	echo "ERROR: Unknown option $1"
+	echo
+	usage
+	exit 1
+	;;
+
+esac
